language: java
before_install:
  - sudo apt-get install gcc-multilib g++-multilib zlib1g:i386 openjdk-6-jdk
install:
  - mkdir __android-sdk__
  - cd __android-sdk__
  - wget -nv http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar -xzf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=${PWD}/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk --filter platform-tools,build-tools-19.1.0,android-19 --no-ui --force
  - ldd android-sdk-linux/build-tools/19.1.0/aapt
  - cd ..
  - mvn install -DskipTests=true -B -V -Djarsigner.skip=true
script:
  - mvn test -B -V
after_script:
  - "[ $TRAVIS_TEST_RESULT -ne 0 ] && head -n 500 target/surefire-reports/*.txt"
